[package]
authors = ["Patrick José Pereira <patrickelectric@gmail.com>"]
description = "Mavlink Camera Manager"
edition = "2021"
license = "MIT"
name = "mavlink-camera-manager"
version = "0.2.4"

documentation = "https://github.com/patrickelectric/mavlink-camera-manager"
homepage = "https://github.com/patrickelectric/mavlink-camera-manager"
readme = "README.md"
repository = "https://github.com/patrickelectric/mavlink-camera-manager"

default-run = "mavlink-camera-manager"
path = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
bench = false
name = "mavlink-camera-manager"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
regex = "1.10.3"

#TODO: Investigate rweb to use openapi spec for free
# https://github.com/kdy1/rweb
actix-files = "0.6.5"
actix-web = "4.5.1"
actix-web-validator = "5.0.1"
actix-service = "2.0.2"
actix-extensible-rate-limit = "0.3.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
validator = { version = "0.16", features = ["derive"] }

## FINAL
sysinfo = "0.29"
chrono = "0.4"
lazy_static = "1.4.0"
include_dir = "0.7.3"
paperclip = { version = "0.8", features = ["paperclip-actix", "actix4",  "swagger-ui", "url", "uuid"] }
#TODO: Replace it with yaserde
quick-xml = { version = "0.31.0", features = ["serialize"] }
url = { version = "2.5.0", features = ["serde"] }
v4l = "0.14.0"
directories = "5.0.1"
pnet = { version = "0.34.0", features = ["std"] }
semver = "1.0"
thirtyfour = "0.31"
tracing = { version = "0.1.40", features = ["log", "async-await"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing-log = "0.2.0"
tracing-actix-web = "0.7.9"
tracing-gstreamer = "0.7.0"
tracing-tracy = { version = "0.10.5", features = ["ondemand", "broadcast"] } # Note that these features defines the tracy client behavior.

# This is a custom revision adding file name suffix on top of tracing-appender-0.2.2" "0.2.2", but compatible with the current tracing version.
# Reference: https://github.com/tokio-rs/tracing/issues/2441
tracing-appender = { git = "https://github.com/joaoantoniocardoso/tracing", branch = "tracing-appender-0.2.2-with-filename-suffix" }

anyhow = "1"
tokio = { version = "1.36", features = ["full"] }
enum_dispatch = "0.3.12"
uuid = { version = "1.7", features = ["v4", "serde"] }
ts-rs = "7.1"
cached = { version = "0.48", features = ["serde", "serde_json", "async_tokio_rt_multi_thread"] }

## Mavlink
mavlink = { version = "0.10.6", features = ["default", "emit-extensions"] }

## WebRTC
async-tungstenite = { version = "0.25", features = ["tokio-runtime", "tokio-native-tls"] }
async-std = { version = "1.12", features =  ["tokio1"] }
futures = "0.3"
webrtc-util = { version = "0.8", default-features = false, features = ["vnet"] }
turn = "0.7"

## Image/Thumbnail
image = "0.24"

## GSTREAMER
# gst = { package = "gstreamer", version = "0.22", features = ["v1_14"] }
gst = { package = "gstreamer", version = "0.22", features = [] }
gst-app = { package = "gstreamer-app", version = "0.22", features = [] }
gst-sdp = { package = "gstreamer-sdp", version = "0.22", features=[] }
gst-webrtc = { package = "gstreamer-webrtc", version = "0.22", features = [] }
gst-rtsp = { package = "gstreamer-rtsp", version = "0.22", features = [] }
gst-rtsp-server = { package = "gstreamer-rtsp-server", version = "0.22", features = [] }
gst-video = { package = "gstreamer-video", version = "0.22", features = [] }
webrtc-sdp = "0.3.11"

[dev-dependencies]
rand = "0.8.5"
serial_test = "0.10"
tracing-test = "0.2"

[build-dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
vergen = { version = "7.5", default-features = false, features = ["build", "git"] }
ts-rs = "7.1"
uuid = { version = "1.7", features = ["v4", "serde"] }
serde = { version = "1.0", features = ["derive"] }
regex = "1"
